[build]
  publish = "manake-web/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[functions]
  directory = "netlify/functions"
