CREATE TABLE IF NOT EXISTS manake_community_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author TEXT NOT NULL DEFAULT 'Community member',
  role TEXT NOT NULL DEFAULT 'Community supporter',
  label TEXT NOT NULL DEFAULT 'Community update',
  body TEXT NOT NULL,
  image_url TEXT,
  image_position TEXT,
  reactions_count INTEGER NOT NULL DEFAULT 0,
  comments_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS manake_support_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_type TEXT NOT NULL CHECK (sender_type IN ('team', 'visitor')),
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS manake_help_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  support_type TEXT NOT NULL,
  urgency TEXT NOT NULL,
  message TEXT,
  status TEXT NOT NULL DEFAULT 'new',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS manake_donation_pledges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount NUMERIC(10, 2) NOT NULL,
  currency TEXT NOT NULL DEFAULT 'USD',
  status TEXT NOT NULL DEFAULT 'pledged',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS manake_auth_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mode TEXT NOT NULL CHECK (mode IN ('login', 'signup')),
  name TEXT,
  email TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'received',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS manake_community_posts_created_at_idx
  ON manake_community_posts (created_at DESC);

CREATE INDEX IF NOT EXISTS manake_support_messages_created_at_idx
  ON manake_support_messages (created_at ASC);

CREATE INDEX IF NOT EXISTS manake_help_requests_status_idx
  ON manake_help_requests (status);

CREATE INDEX IF NOT EXISTS manake_auth_requests_email_idx
  ON manake_auth_requests (email);

INSERT INTO manake_community_posts
  (author, role, label, body, image_url, image_position, reactions_count, comments_count, created_at)
VALUES
  (
    'Tendai M.',
    'Graduate',
    'Recovery win',
    'One year sober this month. Still learning, still showing up, and grateful for the people who kept believing in me.',
    '/images/products/shoesmanake.jpeg',
    '56% 42%',
    1200,
    48,
    NOW() - INTERVAL '3 days'
  ),
  (
    'Life Skills Studio',
    'Programme update',
    'Skills training',
    'Today''s work-readiness session focused on budgeting, punctuality, and building a routine that can last after treatment.',
    NULL,
    NULL,
    870,
    31,
    NOW() - INTERVAL '2 days'
  ),
  (
    'Family Circle',
    'Support group',
    'Family support',
    'Small steps matter. Honest conversations are starting again, and that changes everything for recovery at home.',
    '/images/team/manake.jpeg',
    '50% 45%',
    640,
    22,
    NOW() - INTERVAL '1 day'
  );

INSERT INTO manake_support_messages (sender_type, body, created_at)
VALUES
  (
    'team',
    'Welcome. Tell us what kind of support you need and we will guide the next step.',
    NOW() - INTERVAL '4 minutes'
  ),
  (
    'visitor',
    'I need help for a family member.',
    NOW() - INTERVAL '3 minutes'
  ),
  (
    'team',
    'Thank you for reaching out. Is the situation urgent today?',
    NOW() - INTERVAL '2 minutes'
  );
